//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTVMediaEdit.BTVServer {
    using System.Runtime.Serialization;
    using System;
    
/*
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PVSPropertyBag", Namespace="http://www.snapstream.com/types")]
    [System.SerializableAttribute()]
    public partial class PVSPropertyBag : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PVSProperty[] PropertiesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public PVSProperty[] Properties {
            get {
                return this.PropertiesField;
            }
            set {
                if ((object.ReferenceEquals(this.PropertiesField, value) != true)) {
                    this.PropertiesField = value;
                    this.RaisePropertyChanged("Properties");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PVSProperty", Namespace="http://www.snapstream.com/types")]
    [System.SerializableAttribute()]
    public partial class PVSProperty : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
*/
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.snapstream.com/WebService", ConfigurationName="BTVLicenseManager.BTVLicenseManagerSoap")]
    public interface BTVLicenseManagerSoap {
        
        // CODEGEN: Generating message contract since element name networkLicense from namespace http://www.snapstream.com/WebService is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.snapstream.com/WebService/Logon", ReplyAction="*")]
        LogonResponse Logon(LogonRequest request);
        
        // CODEGEN: Generating message contract since element name authTicket from namespace http://www.snapstream.com/WebService is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.snapstream.com/WebService/ChangePassword", ReplyAction="*")]
        ChangePasswordResponse ChangePassword(ChangePasswordRequest request);
        
        // CODEGEN: Generating message contract since element name authTicket from namespace http://www.snapstream.com/WebService is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.snapstream.com/WebService/RenewLogonSession", ReplyAction="*")]
        RenewLogonSessionResponse RenewLogonSession(RenewLogonSessionRequest request);
        
        // CODEGEN: Generating message contract since element name networkLicense from namespace http://www.snapstream.com/WebService is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.snapstream.com/WebService/LogonRemote", ReplyAction="*")]
        LogonRemoteResponse LogonRemote(LogonRemoteRequest request);
        
        // CODEGEN: Generating message contract since element name ticket from namespace http://www.snapstream.com/WebService is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.snapstream.com/WebService/Logoff", ReplyAction="*")]
        LogoffResponse Logoff(LogoffRequest request);
        
        // CODEGEN: Generating message contract since element name authTicket from namespace http://www.snapstream.com/WebService is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.snapstream.com/WebService/GetPermissionsForTicket", ReplyAction="*")]
        GetPermissionsForTicketResponse GetPermissionsForTicket(GetPermissionsForTicketRequest request);
        
        // CODEGEN: Generating message contract since element name authTicket from namespace http://www.snapstream.com/WebService is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.snapstream.com/WebService/CanChangePassword", ReplyAction="*")]
        CanChangePasswordResponse CanChangePassword(CanChangePasswordRequest request);
        
        // CODEGEN: Generating message contract since element name GetVersionNumberResult from namespace http://www.snapstream.com/WebService is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.snapstream.com/WebService/GetVersionNumber", ReplyAction="*")]
        GetVersionNumberResponse GetVersionNumber(GetVersionNumberRequest request);
        
        // CODEGEN: Generating message contract since element name macAddress from namespace http://www.snapstream.com/WebService is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.snapstream.com/WebService/LogLinkInfo", ReplyAction="*")]
        LogLinkInfoResponse LogLinkInfo(LogLinkInfoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LogonRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Logon", Namespace="http://www.snapstream.com/WebService", Order=0)]
        public LogonRequestBody Body;
        
        public LogonRequest() {
        }
        
        public LogonRequest(LogonRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.snapstream.com/WebService")]
    public partial class LogonRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string networkLicense;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string password;
        
        public LogonRequestBody() {
        }
        
        public LogonRequestBody(string networkLicense, string username, string password) {
            this.networkLicense = networkLicense;
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LogonResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LogonResponse", Namespace="http://www.snapstream.com/WebService", Order=0)]
        public LogonResponseBody Body;
        
        public LogonResponse() {
        }
        
        public LogonResponse(LogonResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.snapstream.com/WebService")]
    public partial class LogonResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public PVSPropertyBag LogonResult;
        
        public LogonResponseBody() {
        }
        
        public LogonResponseBody(PVSPropertyBag LogonResult) {
            this.LogonResult = LogonResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ChangePasswordRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ChangePassword", Namespace="http://www.snapstream.com/WebService", Order=0)]
        public ChangePasswordRequestBody Body;
        
        public ChangePasswordRequest() {
        }
        
        public ChangePasswordRequest(ChangePasswordRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.snapstream.com/WebService")]
    public partial class ChangePasswordRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string authTicket;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string oldPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string newPassword;
        
        public ChangePasswordRequestBody() {
        }
        
        public ChangePasswordRequestBody(string authTicket, string oldPassword, string newPassword) {
            this.authTicket = authTicket;
            this.oldPassword = oldPassword;
            this.newPassword = newPassword;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ChangePasswordResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ChangePasswordResponse", Namespace="http://www.snapstream.com/WebService", Order=0)]
        public ChangePasswordResponseBody Body;
        
        public ChangePasswordResponse() {
        }
        
        public ChangePasswordResponse(ChangePasswordResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.snapstream.com/WebService")]
    public partial class ChangePasswordResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool ChangePasswordResult;
        
        public ChangePasswordResponseBody() {
        }
        
        public ChangePasswordResponseBody(bool ChangePasswordResult) {
            this.ChangePasswordResult = ChangePasswordResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RenewLogonSessionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RenewLogonSession", Namespace="http://www.snapstream.com/WebService", Order=0)]
        public RenewLogonSessionRequestBody Body;
        
        public RenewLogonSessionRequest() {
        }
        
        public RenewLogonSessionRequest(RenewLogonSessionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.snapstream.com/WebService")]
    public partial class RenewLogonSessionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string authTicket;
        
        public RenewLogonSessionRequestBody() {
        }
        
        public RenewLogonSessionRequestBody(string authTicket) {
            this.authTicket = authTicket;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RenewLogonSessionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RenewLogonSessionResponse", Namespace="http://www.snapstream.com/WebService", Order=0)]
        public RenewLogonSessionResponseBody Body;
        
        public RenewLogonSessionResponse() {
        }
        
        public RenewLogonSessionResponse(RenewLogonSessionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.snapstream.com/WebService")]
    public partial class RenewLogonSessionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool RenewLogonSessionResult;
        
        public RenewLogonSessionResponseBody() {
        }
        
        public RenewLogonSessionResponseBody(bool RenewLogonSessionResult) {
            this.RenewLogonSessionResult = RenewLogonSessionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LogonRemoteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LogonRemote", Namespace="http://www.snapstream.com/WebService", Order=0)]
        public LogonRemoteRequestBody Body;
        
        public LogonRemoteRequest() {
        }
        
        public LogonRemoteRequest(LogonRemoteRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.snapstream.com/WebService")]
    public partial class LogonRemoteRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string networkLicense;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string password;
        
        public LogonRemoteRequestBody() {
        }
        
        public LogonRemoteRequestBody(string networkLicense, string username, string password) {
            this.networkLicense = networkLicense;
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LogonRemoteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LogonRemoteResponse", Namespace="http://www.snapstream.com/WebService", Order=0)]
        public LogonRemoteResponseBody Body;
        
        public LogonRemoteResponse() {
        }
        
        public LogonRemoteResponse(LogonRemoteResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.snapstream.com/WebService")]
    public partial class LogonRemoteResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public PVSPropertyBag LogonRemoteResult;
        
        public LogonRemoteResponseBody() {
        }
        
        public LogonRemoteResponseBody(PVSPropertyBag LogonRemoteResult) {
            this.LogonRemoteResult = LogonRemoteResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LogoffRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Logoff", Namespace="http://www.snapstream.com/WebService", Order=0)]
        public LogoffRequestBody Body;
        
        public LogoffRequest() {
        }
        
        public LogoffRequest(LogoffRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.snapstream.com/WebService")]
    public partial class LogoffRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ticket;
        
        public LogoffRequestBody() {
        }
        
        public LogoffRequestBody(string ticket) {
            this.ticket = ticket;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LogoffResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LogoffResponse", Namespace="http://www.snapstream.com/WebService", Order=0)]
        public LogoffResponseBody Body;
        
        public LogoffResponse() {
        }
        
        public LogoffResponse(LogoffResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class LogoffResponseBody {
        
        public LogoffResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPermissionsForTicketRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPermissionsForTicket", Namespace="http://www.snapstream.com/WebService", Order=0)]
        public GetPermissionsForTicketRequestBody Body;
        
        public GetPermissionsForTicketRequest() {
        }
        
        public GetPermissionsForTicketRequest(GetPermissionsForTicketRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.snapstream.com/WebService")]
    public partial class GetPermissionsForTicketRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string authTicket;
        
        public GetPermissionsForTicketRequestBody() {
        }
        
        public GetPermissionsForTicketRequestBody(string authTicket) {
            this.authTicket = authTicket;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPermissionsForTicketResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPermissionsForTicketResponse", Namespace="http://www.snapstream.com/WebService", Order=0)]
        public GetPermissionsForTicketResponseBody Body;
        
        public GetPermissionsForTicketResponse() {
        }
        
        public GetPermissionsForTicketResponse(GetPermissionsForTicketResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.snapstream.com/WebService")]
    public partial class GetPermissionsForTicketResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetPermissionsForTicketResult;
        
        public GetPermissionsForTicketResponseBody() {
        }
        
        public GetPermissionsForTicketResponseBody(string GetPermissionsForTicketResult) {
            this.GetPermissionsForTicketResult = GetPermissionsForTicketResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CanChangePasswordRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CanChangePassword", Namespace="http://www.snapstream.com/WebService", Order=0)]
        public CanChangePasswordRequestBody Body;
        
        public CanChangePasswordRequest() {
        }
        
        public CanChangePasswordRequest(CanChangePasswordRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.snapstream.com/WebService")]
    public partial class CanChangePasswordRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string authTicket;
        
        public CanChangePasswordRequestBody() {
        }
        
        public CanChangePasswordRequestBody(string authTicket) {
            this.authTicket = authTicket;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CanChangePasswordResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CanChangePasswordResponse", Namespace="http://www.snapstream.com/WebService", Order=0)]
        public CanChangePasswordResponseBody Body;
        
        public CanChangePasswordResponse() {
        }
        
        public CanChangePasswordResponse(CanChangePasswordResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.snapstream.com/WebService")]
    public partial class CanChangePasswordResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool CanChangePasswordResult;
        
        public CanChangePasswordResponseBody() {
        }
        
        public CanChangePasswordResponseBody(bool CanChangePasswordResult) {
            this.CanChangePasswordResult = CanChangePasswordResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetVersionNumberRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetVersionNumber", Namespace="http://www.snapstream.com/WebService", Order=0)]
        public GetVersionNumberRequestBody Body;
        
        public GetVersionNumberRequest() {
        }
        
        public GetVersionNumberRequest(GetVersionNumberRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetVersionNumberRequestBody {
        
        public GetVersionNumberRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetVersionNumberResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetVersionNumberResponse", Namespace="http://www.snapstream.com/WebService", Order=0)]
        public GetVersionNumberResponseBody Body;
        
        public GetVersionNumberResponse() {
        }
        
        public GetVersionNumberResponse(GetVersionNumberResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.snapstream.com/WebService")]
    public partial class GetVersionNumberResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetVersionNumberResult;
        
        public GetVersionNumberResponseBody() {
        }
        
        public GetVersionNumberResponseBody(string GetVersionNumberResult) {
            this.GetVersionNumberResult = GetVersionNumberResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LogLinkInfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LogLinkInfo", Namespace="http://www.snapstream.com/WebService", Order=0)]
        public LogLinkInfoRequestBody Body;
        
        public LogLinkInfoRequest() {
        }
        
        public LogLinkInfoRequest(LogLinkInfoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.snapstream.com/WebService")]
    public partial class LogLinkInfoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string macAddress;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string authticket;
        
        public LogLinkInfoRequestBody() {
        }
        
        public LogLinkInfoRequestBody(string macAddress, string authticket) {
            this.macAddress = macAddress;
            this.authticket = authticket;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LogLinkInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LogLinkInfoResponse", Namespace="http://www.snapstream.com/WebService", Order=0)]
        public LogLinkInfoResponseBody Body;
        
        public LogLinkInfoResponse() {
        }
        
        public LogLinkInfoResponse(LogLinkInfoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class LogLinkInfoResponseBody {
        
        public LogLinkInfoResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface BTVLicenseManagerSoapChannel : BTVLicenseManagerSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class BTVLicenseManagerSoapClient : System.ServiceModel.ClientBase<BTVLicenseManagerSoap>, BTVLicenseManagerSoap {
        
        public BTVLicenseManagerSoapClient() {
        }
        
        public BTVLicenseManagerSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BTVLicenseManagerSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BTVLicenseManagerSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BTVLicenseManagerSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LogonResponse BTVLicenseManagerSoap.Logon(LogonRequest request) {
            return base.Channel.Logon(request);
        }
        
        public PVSPropertyBag Logon(string networkLicense, string username, string password) {
            LogonRequest inValue = new LogonRequest();
            inValue.Body = new LogonRequestBody();
            inValue.Body.networkLicense = networkLicense;
            inValue.Body.username = username;
            inValue.Body.password = password;
            LogonResponse retVal = ((BTVLicenseManagerSoap)(this)).Logon(inValue);
            return retVal.Body.LogonResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ChangePasswordResponse BTVLicenseManagerSoap.ChangePassword(ChangePasswordRequest request) {
            return base.Channel.ChangePassword(request);
        }
        
        public bool ChangePassword(string authTicket, string oldPassword, string newPassword) {
            ChangePasswordRequest inValue = new ChangePasswordRequest();
            inValue.Body = new ChangePasswordRequestBody();
            inValue.Body.authTicket = authTicket;
            inValue.Body.oldPassword = oldPassword;
            inValue.Body.newPassword = newPassword;
            ChangePasswordResponse retVal = ((BTVLicenseManagerSoap)(this)).ChangePassword(inValue);
            return retVal.Body.ChangePasswordResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RenewLogonSessionResponse BTVLicenseManagerSoap.RenewLogonSession(RenewLogonSessionRequest request) {
            return base.Channel.RenewLogonSession(request);
        }
        
        public bool RenewLogonSession(string authTicket) {
            RenewLogonSessionRequest inValue = new RenewLogonSessionRequest();
            inValue.Body = new RenewLogonSessionRequestBody();
            inValue.Body.authTicket = authTicket;
            RenewLogonSessionResponse retVal = ((BTVLicenseManagerSoap)(this)).RenewLogonSession(inValue);
            return retVal.Body.RenewLogonSessionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LogonRemoteResponse BTVLicenseManagerSoap.LogonRemote(LogonRemoteRequest request) {
            return base.Channel.LogonRemote(request);
        }
        
        public PVSPropertyBag LogonRemote(string networkLicense, string username, string password) {
            LogonRemoteRequest inValue = new LogonRemoteRequest();
            inValue.Body = new LogonRemoteRequestBody();
            inValue.Body.networkLicense = networkLicense;
            inValue.Body.username = username;
            inValue.Body.password = password;
            LogonRemoteResponse retVal = ((BTVLicenseManagerSoap)(this)).LogonRemote(inValue);
            return retVal.Body.LogonRemoteResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LogoffResponse BTVLicenseManagerSoap.Logoff(LogoffRequest request) {
            return base.Channel.Logoff(request);
        }
        
        public void Logoff(string ticket) {
            LogoffRequest inValue = new LogoffRequest();
            inValue.Body = new LogoffRequestBody();
            inValue.Body.ticket = ticket;
            LogoffResponse retVal = ((BTVLicenseManagerSoap)(this)).Logoff(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GetPermissionsForTicketResponse BTVLicenseManagerSoap.GetPermissionsForTicket(GetPermissionsForTicketRequest request) {
            return base.Channel.GetPermissionsForTicket(request);
        }
        
        public string GetPermissionsForTicket(string authTicket) {
            GetPermissionsForTicketRequest inValue = new GetPermissionsForTicketRequest();
            inValue.Body = new GetPermissionsForTicketRequestBody();
            inValue.Body.authTicket = authTicket;
            GetPermissionsForTicketResponse retVal = ((BTVLicenseManagerSoap)(this)).GetPermissionsForTicket(inValue);
            return retVal.Body.GetPermissionsForTicketResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CanChangePasswordResponse BTVLicenseManagerSoap.CanChangePassword(CanChangePasswordRequest request) {
            return base.Channel.CanChangePassword(request);
        }
        
        public bool CanChangePassword(string authTicket) {
            CanChangePasswordRequest inValue = new CanChangePasswordRequest();
            inValue.Body = new CanChangePasswordRequestBody();
            inValue.Body.authTicket = authTicket;
            CanChangePasswordResponse retVal = ((BTVLicenseManagerSoap)(this)).CanChangePassword(inValue);
            return retVal.Body.CanChangePasswordResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GetVersionNumberResponse BTVLicenseManagerSoap.GetVersionNumber(GetVersionNumberRequest request) {
            return base.Channel.GetVersionNumber(request);
        }
        
        public string GetVersionNumber() {
            GetVersionNumberRequest inValue = new GetVersionNumberRequest();
            inValue.Body = new GetVersionNumberRequestBody();
            GetVersionNumberResponse retVal = ((BTVLicenseManagerSoap)(this)).GetVersionNumber(inValue);
            return retVal.Body.GetVersionNumberResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LogLinkInfoResponse BTVLicenseManagerSoap.LogLinkInfo(LogLinkInfoRequest request) {
            return base.Channel.LogLinkInfo(request);
        }
        
        public void LogLinkInfo(string macAddress, string authticket) {
            LogLinkInfoRequest inValue = new LogLinkInfoRequest();
            inValue.Body = new LogLinkInfoRequestBody();
            inValue.Body.macAddress = macAddress;
            inValue.Body.authticket = authticket;
            LogLinkInfoResponse retVal = ((BTVLicenseManagerSoap)(this)).LogLinkInfo(inValue);
        }
    }
}
